spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: hello-service
          uri: http://hello-service-rest.backend.svc.cluster.local:8080
          predicates:
            - Path=/hello/**
          filters:
            - RewritePath=/hello/(?<segment>.*), /$\{segment}
        - id: test-service
          uri: http://test-service-rest.backend.svc.cluster.local:8080
          predicates:
            - Path=/test/**
          filters:
            - RewritePath=/test/(?<segment>.*), /$\{segment}
        - id: echo-service
          uri: https://echo.free.beeceptor.com
          predicates:
            - Path=/echo/**
          filters:
            - RewritePath=/echo/(?<segment>.*), /$\{segment}

# http://hello-service-rest.backend.svc.cluster.local:8080
# lb://hello-service-rest.backend.svc.cluster.local:8080
